### ISSUE TITLE
Feature: Devise (or other) User auth

### ISSUE THREAD

**Issue by wassson** [caley-io/caley#26]
This is just to start a conversation, but in my opinion we should use Devise and CanCanCan (or Pundit) for our user auth rather than rolling our own. Devise will be infinitely more secure that anything we could get going quick enough for a launch. Any thoughts or discussions already happening around this?

**Comment by jeremyscatigna** [comment]
That definitely make sense, rolling our own auth is not a good idea for a production product don't hesitate to create a proper issue for the implementation @wassson

**Comment by wassson** [comment]
Awesome. Confirming that this issue is now a feature for integrating Devise as our auth system. Assigning it to myself.

**Comment by diegolinhares** [comment]
Why not use authentication-zero?
It uses Rails default authentication. It's just a template.

One more thing I saw you are generating tokens for the Invite model. You could use a new method from Rails called **generates_token_for** and eliminate all that code.

**Comment by al3rez** [comment]
I decided to go with the default Ruby on Rails authentication system, which is secure enough and we don't user any extra features from Devise so I will close this ticket.
