### ISSUE TITLE
Feature: Workspace/Teams model

### ISSUE THREAD

**Issue by jeremyscatigna** [caley-io/caley#5]
### Type of feature

💡 Feature

### Current behavior

None

### Suggested solution

We need to implement a Workspace/Teams model
Details: The goal here is to enable support for Workspace/Teams just like in Slack you could have multiple workspaces for example one that is your personal workspace composed of all your personal email addresses and others for companies or teams

It involves:

- Creating a new workspace
- Invite team member or not to workspace + assigning roles (email invitation)
- Add multiple Gmail or Google workspaces accounts to a workspace (for later)

Here is the layout I have in mind:
<img width="1021" alt="Multitenancy Teams Workspaces" src="https://github.com/caley-io/caley/assets/15782436/2090ebc8-17df-4bd1-8bd0-ec15b76ce2a2">

Just like Slack it would be cool to have a left bar With Workspaces

For the flow:

- When a user signup it should create a personal Workspace
- In the workspace the user could add multiple Google accounts
- The user could create New workspaces
- A user could invite people to join the workspace (email invite)
- A user could Update the workspace name and logo
- The user could add roles to people on his team

**Comment by wassson** [comment]
This should be pretty straight forward! We need a `workspaces` table and a `workspace_users` join table that `belongs_to` both `workspace` and `user`. We can set the workspace id in the session just like we do with the user. Rails will take care of the rest!

As a side note - any thoughts on this kind of design (notion's workspace picker)? In my opinion, I wouldn't be switching workspaces enough to always need the workspace column open, so this could be a good solution! Just food for thought.

<img width="387" alt="Screenshot 2024-02-12 at 5 16 51 PM" src="https://github.com/caley-io/caley/assets/93844519/5ad0247e-244a-4012-bf7a-67012ff5ed07">
